name: WEBAPP onm Docker stack with Compose.yml

services:
  db:
    image: mariadb:10.11
    container_name: db
    restart: always
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d #Dump file is entrypoint initialization database
      - ./mysql-db:/var/lib/mysql
    
    environment:
      - "MARIADB_DATABASE=testdb"
      - "MARIADB_USER=testc"
      - "MARIADB_PASSWORD=P@ssw0rd"
      - "MARIADB_ROOT_PASSWORD=qwerty1!"
    

  tespapp:
    image: site:latest
    container_name: tespapp
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8000

    environment:
      - "DB_TYPE=maria" 
      - "DB_HOST=db"
      - "DB_NAME=testdb"
      - "DB_PORT=3306"
      - "DB_USER=testc"
      - "DB_PASS=P@ssw0rd"

